### ISSUE TITLE
ISU0033 Upgrade the system to use Django Version 2

### ISSUE THREAD

**Issue by nherriot** [nherriot/noisy-atom-portal#33]
The current version of Django uses version 1.10. However, this only supports version 2.7, 3.4 and 3.5 of python. You can find details here:

https://docs.djangoproject.com/en/dev/releases/1.10/

We need to update the system to use Django 2.2. This may require fixes to the code base to make sure that it is also compatible with Django 2.2.

From following the documentation readme.md here:

https://github.com/nherriot/noisy-atom-portal/tree/master/documentation#check-the-django-application-works

It fails on line: 132
```
/> python manage.py runserver
```

The task is to get this to run with requirements.txt setting django version to 2.2.

**Comment by DilshadGit** [comment]
Update django version from django==1.10.5 to django==2.2.27 DONE
This automatically install 2 packages with django which ( pytz=2021.3 and sqlparse==0.4.2 DONE
from django.core.urlresolve import reverse update it to django.urls import reverse DONE
Add on_delete=models.CASCADE to ForeignKey fields DONE
Add name of the application (app_name = "appname") to each urls.py DONE
Change MIDDLEWARE_CLASS to MIDDLEWARE in djnago==2.2.27 DONE
Removed 'django.contrib.auth.middleware.SessionAuthenticationMiddleware', in settings.py DONE
Delete all migrations file except init.py DONE
Delete database run following commands DONE
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
login to admin page create one post of all apps for testing process.

**Comment by nherriot** [comment]
This is now done and merged to master.
