### ISSUE TITLE
Pillow recommended version 6 for python3.8

### ISSUE THREAD

**Issue by DilshadGit** [nherriot/noisy-atom-portal#49]
Please check the link:
https://pillow.readthedocs.io/en/latest/installation.html

For Mac OS the pip install pillow==4.0.0 failed.

`
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         http://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow`

**Comment by nherriot** [comment]
Closed with pull request: https://github.com/nherriot/noisy-atom-portal/pull/51
